### ISSUE TITLE
Es correcta esta implementacion desde el punto de vista de diseño?

### ISSUE THREAD

**Issue by gmenendez0** [gmenendez0/Calendar#1]
https://github.com/gmenendez0/Calendar/blob/cb8f7ea63f46d89b4597a2f34341c96ec290e9c0/src/main/java/org/calendar/Task.java#L15

Hola

Queria consultar si la implementacion que elegi es correcta desde el punto de vista del diseño:
Basicamente, yo tengo un objeto tarea con dos constructores, un contructor acepta una fecha de inicio y el otro cosntructor acepta una fecha y hora de expiracion. 
-Si se llama al constructor que acepta una fecha y hora, se interpreta que la fecha y hora es el momento puntual de expiracion.
-Si se llama al constructor que acepta una fecha, se interpreta que esa fecha representa el dia de la tarea y que dicha tarea es de dia completo, entonces el propio objeto tarea se ocupa de asignarse a si mismo su fecha de expiracion como las 00:00 del dia siguiente al dia recido.

Mi pregunta es:
Es correcto que el objeto Tarea sea el que deduzca si es dia completo o no? O lo correcto seria que al objeto tarea le llegue solo una fecha y hora de expiracion con un atributo diaCompleto y que la logica de enviar fecha y hora de expiracion correcta se haga desde fuera del objeto Tarea?

**Comment by dcorsi** [comment]
A ver si entendí tu propuesta:

Triangulo trianguloEquilatero = new Triangulo (3);
Triangulo trianguloIsosceles = new Triangulo (3, 4);  // Por convención, se interpreta que el lado repetido es el primero: 3
Triangulo trianguloEscaleno = new Triangulo (3, 4, 5);

El ejemplo anterior muestra un diseño pobre, pues no hay una jerarquía de clases de triángulos.

Triangulo trianguloEquilatero = new TrianguloEquilatero (3);
Triangulo trianguloIsosceles1 = new TrianguloIsosceles (3, 4); // Por convención, se interpreta que el lado repetido es el primero: 3
Triangulo trianguloIsosceles2 = new TrianguloIsosceles (3, 4, 3); // La sobrecarga permite no depender de la convención
Triangulo trianguloEscaleno = new TrianguloEscaleno (3, 4, 5);

Las variables en esta versión son polimórficas, hay una jerarquía de clases (herencia), y la sobrecarga permite ofrecer alternativas al programador, pero las variantes del constructor NO generan DISTINTOS TIPOS de triángulos...

A ver si los ejemplos fueron clarificadores... Saludos!

**Comment by gmenendez0** [comment]
A ver si yo entendi bien tu respuesta:

Vos me sugeris que un mejor diseño seria, asi como vos clasificas las subclases de Triangulo en base a la longitud de sus lados, yo podria clasificar las subclases de Tarea en base a su "duracion" (wholeDay o no)?

Se que duracion no es la mejor palabra para usar porque las tareas en si tienen fecha y hora de expiracion, no "duracion", pero creo que se entiende a lo que me refiero con el wholeDay.

Gracias!

**Comment by dcorsi** [comment]
Exacto. Sería una mejor implementación... Porque entendí que vos querías distinguir entre dos tipos de tareas según cómo las instanciás:
new Tarea(fecha)
new Tarea(fecha, hora)
Y usar un atributo para diferenciar los objetos de un tipo u otro...
En principio tu enfoque funcionaría, pero cómo lo escalarías si te pedimos tareas de medio día? Agregando otro atributo más para distinguir los objetos?

**Comment by gmenendez0** [comment]
Muy bien, ya lo estructure de otra manera para que quede escalable. Cierro el issue.

Muchas gracias!
