### ISSUE TITLE
Etapa 1

### ISSUE THREAD

**Issue by gmenendez0** [gmenendez0/Calendar#3]
Aclaracion, por las dudas:
-Las alarmas no estan testeadas porque no tienen logica dentro aun. Lo unico que tienen es un Print que esta hecho a proposito para saber que el metodo Ring() esta siendo llamado, luego este print sera removido.

**Comment by dcorsi** [comment]
Me pareció bien presentado el trabajo (lo mejor es el uso de _decorator_ para eventualmente permitir combinar distintos tipos de efectos de alarmas), aunque algunos detalles hacen que se requiera una reentrega (tienen hasta el 8/5 a las 23:59 inclusive).
1) Faltó la repetición de los eventos.
2) Faltó la alarma en instante relativo.
3) Faltó implementar los toques de alarmas como funciones testeables (que retornen un valor además de tener el efecto que simularon con prints - los cuales deberían borrar antes de la reentrega) y los correspondientes tests.
4) Las pruebas deben ser determinísticas (cada vez que se corran deben usar los mismos datos). Esto si usan `now()` no lo consiguen.
5) No me parece mal que usen nombres en inglés para los identificadores (aunque aportan algo de complejidad cuando el enunciado no fue entregado en esa lengua). Sin embargo, tengan cuidado cuando es una lengua extranjera: en inglés se denomina _**diary**_ a un _**diario**_ como el de Bridget Jones (https://en.wikipedia.org/wiki/Bridget_Jones%27s_Diary)... En cambio, cuando un evento es _**diario**_, en inglés se dice que es _a **daily** event_.

[Evaluación primera entrega.pdf](https://github.com/gmenendez0/Calendar/files/11360430/Evaluacion.primera.entrega.pdf)

**Comment by dcorsi** [comment]
Como les decía, el trabajo me pareció bien presentado, y disculpen si la comunicación no ha sido 100% fluida (quizás deberíamos requerir un informe escrito además del código, para entender mejor sus decisiones de diseño).
1. OK, la repetición de los eventos está parcialmente implementada y lo que falta lo pueden implementar en una entrega posterior (no en esta reentrega).
2. OK, la alarma en instante relativo la pueden implementar en una entrega posterior (no en esta reentrega).
3. El dedito levantado en Slack era por el 50% de cobertura que es lo mínimo aceptable. Arreglen esto para la reentrega: si en lugar de usar prints en `ring`, hacen que retorne algo verificable, `ring` ya sería testeable. Como están usando _decorator_, podrían retornar un conjunto de efectos y en los _tests_ chequear si el conjunto contiene los efectos esperados.
4. Arréglenlo para la reentrega.
5. Arréglenlo para la reentrega. 
[Evaluación primera entrega.pdf](https://github.com/gmenendez0/Calendar/files/11360992/Evaluacion.primera.entrega.pdf)

**Comment by mauroj4ckunas** [comment]
Buenas tardes Diego, ya arreglamos los puntos 3, 4 y 5. Al ver el pdf  'Evaluación primera entrega' vimos que no estaban tildados los puntos 6)d)i) (que habla de los eventos infinitos) y el 6)e) (la modificación de un evento también repercute en sus repeticiones), ambos puntos ya están diseñados.
En los dos puntos es el mismo caso que nos recalco en las correcciones 1 y 2, osea que la lógica está hecha pero se debe implementar en las siguientes etapas. La lógica la escribió mi compañero y está subida en la carpeta 'doc' en el git, en "Calendar.txt". Entonces, al modificar un evento, sus copias se crearan ya con esa modificación.
Y en el caso de las repeticiones infinitas: la clase 'Event' tiene un metodo que nos devuelve la siguiente fecha del evento, entonces con esta crearemos (cuando lo necesitemos en la funcion de obtener eventos entre dos fechas) la repetición del evento. Agregué un nuevo test (en "wholeDayEventTest.java") que prueba este método en un evento infinito, y como consecuencia se repitió el evento un MILLÓN de veces (simulando la infinidad). 
Para que el evento sea infinito o no dependerá de la frecuencia, de que si tiene un "deadline" o fecha limite.

**Comment by dcorsi** [comment]
Hola!
Se les escapó la violación de un principio en `Alarm.update()`.
¿Podrían decirme cuál es y arreglarlo? Está relacionado con el punto 4 del listado anterior...
El resto ya estaría todo bien.

**Comment by gmenendez0** [comment]
Buenas

Entiendo que estamos rompiendo POLK en esta linea:
https://github.com/gmenendez0/Calendar/blob/26c784366b448cc4d2e2f4bf97c24fa89fff958f/src/main/java/org/calendar/alarms/Alarm.java#L24

Para solucionarlo consideramos que "Update" reciba time.now() por parametro. Pero si nos ponemos muy al milimetro, desde que se crea el valor time.now() hasta que se ejecuta el If() que te cite, el tiempo cambio, entonces no estaria haciendo la verificacion con el tiempo actual.
No conozco los tiempos de java, se que al ser alto nivel pueden ser altos, pero me preocupa que al hacer la comparacion con un tiempo "desactualizado" pueda llevar a errores en casos muuuy puntuales.

No se si se entiende o si me estoy explicando bien.

**Comment by dcorsi** [comment]
Principalmente estaban violando EDP...
La solución propuesta fue correcta, porque ahora `update` depende explícitamente de `LocalDateTime`.
El problema que mencionás no me parece relevante en este tipo de aplicaciones... El tiempo "congelado" por el cliente de `Alarm` normalmente llegará al `if` en mucho menos de un segundo... 
A propósito, `Appointment.checkAlarms()` también debe recibir `LocalDateTime.now()`...

**Comment by dcorsi** [comment]
Ya los pasé a `Aprobado`... Me pareció muy productivo el intercambio con este equipo!

**Comment by gmenendez0** [comment]
Le pifeamos el nombre del principio pero la idea era esa. En estos dias lo estaremos solucionando.

Gracias! Saludos.
